phpsu/phpsu

- .github/stale.yml
> [FEATURE] Adding Stale to phpsu branches

- composer.json
- docs/CommandLine/SyncCommand.md
- docs/CommandLine/index.md
- phpsu
- src/CommandController.php
- src/Console/AbstractCommand.php
- src/Console/SyncCommand.php
- tests/ConsoleTest.php
Resolves Issue: #6 
**In this Pull Request**
> [FEATURE] parsing the sync direction

- README.md
documentation for testing lacked the watch operator
> testing in the readme

- src/Command/RsyncCommand.php
- tests/Cli/SyncCliCommandTest.php
- tests/Command/CommandGeneratorTest.php
- tests/Command/RsyncCommandTest.php
- tests/Config/GlobalConfigTest.php
- tests/ControllerTest.php
See issue https://github.com/phpsu/phpsu/issues/66
> [BUGFIX] Remove * from rsync source folder

- .github/PULL_REQUEST_TEMPLATE.md
> shorten the PULL_REQUEST_TEMPLATE

- docs/CommandLine/Sync.md
- docs/CommandLine/index.md
- docs/index.md
- src/Cli/SyncCliCommand.php
> resturcture sync options #62

- src/Command/DatabaseCommand.php
- tests/Command/CommandGeneratorTest.php
- tests/Command/DatabaseCommandTest.php
- tests/ControllerTest.php
Closes: #57
It is simpler to sync a system if that system wasn't present bevor.
The change was tested locally wich a Test Project.
> :sparkles: #57 add create database if not exists to DatabaseCommand

- docs/CommandLine/index.md
> :pencil2: fix markdown

- src/Command/DatabaseCommand.php
> :ok_hand: Apply suggestions from code review

- README.md
- tests/Config/GlobalConfigTest.php
will add mutation testing with configured threshold.
TODO:
> :white_check_mark::heavy_plus_sign: add infection to travis

- box.json
- src/Helper/ApplicationHelper.php
I just stumbled across humbug/box. It is very nice.
related: #102
It would be very nice If phpsu could be used as .phar file.
> add support for a phpsu.phar file

- src/Config/GlobalConfig.php
- tests/Command/CommandGeneratorTest.php
- tests/Config/GlobalConfigTest.php
> add SSH Config ServerAliveInterval to default config

- src/Cli/SyncCliCommand.php
- src/Config/ConfigurationLoader.php
- src/Controller.php
- src/ControllerInterface.php
- tests/Cli/SyncCliCommandTest.php
- tests/Config/AppInstanceTest.php
- tests/Config/AppInstancesTest.php
- tests/Config/ConfigurationLoaderTest.php
- tests/Config/GlobalConfigTest.php
> :sparkles: check ssh connection before sync

- composer.json
- src/Command/DatabaseCommand.php
- src/Config/AppInstance.php
- src/Config/Compression/Bzip2Compression.php
- src/Config/Compression/CompressionInterface.php
- src/Config/Compression/EmptyCompression.php
- src/Config/Compression/GzipCompression.php
- tests/Command/CommandGeneratorTest.php
- tests/Command/DatabaseCommandTest.php
- tests/Config/AppInstanceTest.php
- tests/ControllerTest.php
> :sparkles: #61 add compression to database

- src/Command/DatabaseCommand.php
- tests/Command/CommandGeneratorTest.php
- tests/Command/DatabaseCommandTest.php
- tests/ControllerTest.php
https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html#option_mysqldump_single-transaction
> :sparkles: now uses --single-transaction --lock-tables=false

- README.md
> :pencil: fixed typo

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- docs/CommandLine/Sync.md
- docs/index.md
> ✏️ update documenation wording

- .travis.yml
- Dockerfile
- composer.json
- src/Cli/SshCliCommand.php
- src/Command/CommandGenerator.php
- src/Command/CommandInterface.php
- src/Command/DatabaseCommand.php
- src/Command/RsyncCommand.php
- src/Command/SshCommand.php
- src/Config/Compression/Bzip2Compression.php
- src/Config/Compression/GzipCompression.php
- src/Controller.php
- src/Helper/StringHelper.php
- src/Options/SshOptions.php
- src/Process/CommandExecutor.php
- src/Tools/EnvironmentUtility.php
- tests/Cli/SshCliCommandTest.php
- tests/Cli/SyncCliCommandTest.php
- tests/Command/CommandGeneratorTest.php
- tests/Command/DatabaseCommandTest.php
- tests/Command/RsyncCommandTest.php
- tests/Command/SshCommandTest.php
- tests/ControllerTest.php
> implement first draft of shell script generation

- src/Command/DatabaseCommand.php
- tests/Command/CommandGeneratorTest.php
- tests/Command/DatabaseCommandTest.php
- tests/ControllerTest.php
> making the mysql* commands more explicit

- src/Config/Database.php
- tests/Command/CommandGeneratorTest.php
- tests/Command/DatabaseCommandTest.php
- tests/ControllerTest.php
> Breaking Change: noDefiner is true by default

- .gitattributes
- .github/workflows/main.yml
- docker-compose.yml
- src/Command/DatabaseCommand.php
- tests/Command/CommandGeneratorTest.php
- tests/Command/DatabaseCommandTest.php
- tests/ControllerTest.php
> ✨ add --no-tablespaces and --complete-insert

- .github/workflows/main.yml
- phpstan-baseline.neon
- src/Command/DatabaseCommand.php
- src/Config/Database.php
- src/Tools/EnvironmentUtility.php
- tests/Command/CommandGeneratorTest.php
- tests/Command/DatabaseCommandTest.php
- tests/ControllerTest.php
- tests/Process/CommandExecutorTest.php
Read more about it here:
https://mariadb.org/mariadb-dump-file-compatibility-change/
- default setting is to remove the sandbox mode
> 🐛 mariadb added sandbox mode to the mysql-dump command

- src/Command/SshCommand.php
- src/Controller.php
- src/Process/CommandExecutor.php
- tests/Process/CommandExecutorTest.php
- tests/phpunit-bootstrap.php
> ✨ use stdin for phpsu mysql command

- src/Command/DatabaseCommand.php
- tests/Command/CommandGeneratorTest.php
- tests/Command/DatabaseCommandTest.php
- tests/ControllerTest.php
> 🐛 fix exit codes of database sync
